---
fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt
    archive: https://github.com/voxpupuli/puppet-archive
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    systemd: https://github.com/voxpupuli/puppet-systemd
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core
