---
fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    apt: 'https://github.com/puppetlabs/puppetlabs-apt'
    archive: 'https://github.com/voxpupuli/puppet-archive'
    epel: 'https://github.com/voxpupuli/puppet-epel'
    systemd: 'https://github.com/voxpupuli/puppet-systemd'
    yumrepo_core: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core'
